export const AuthActions = {
  SET_LOADER: "SET_LOADER",
  SET_USER_DATA: "SET_USER_DATA",
  SET_AUTH_TOKEN: "SET_AUTH_TOKEN",
  SET_ERROR: "SET_ERROR",
};

export const DataActions = {
  SET_LOADER: "SET_LOADER",
  SET_SELECTED_DATE: "SET_SELECTED_DATE",
  SET_INCOME_DATA: "SET_INCOME_DATA",
  SET_EXPENSE_DATA: "SET_EXPENSE_DATA",
  ADD_EXPENSE: "ADD_EXPENSE",
  ADD_INCOME: "ADD_INCOME",
  REMOVE_EXPENSE: "REMOVE_EXPENSE",
  REMOVE_INCOME: "REMOVE_INCOME",
  UPDATE_INCOME_EXPENSE: "UPDATE_INCOME_EXPENSE",
};
