export const AuthActions = {
  SET_USERNAME: "SET_USERNAME",
  SET_PASSWORD: "SET_PASSWORD",
  SET_EMAIL: "SET_EMAIL",
  SET_LOGIN_FLAG: "SET_LOGIN_FLAG",
};

export const DataActions = {
  SET_SELECTED_DATE: "SET_SELECTED_DATE",
};
