export const AuthActions = {
  SET_USERNAME: "SET_USERNAME",
  SET_PASSWORD: "SET_PASSWORD",
  SET_EMAIL: "SET_EMAIL",
  SET_LOGIN_FLAG: "SET_LOGIN_FLAG",
};

export const DataActions = {
  SET_SELECTED_DATE: "SET_SELECTED_DATE",
  ADD_EXPENSE: "ADD_EXPENSE",
  ADD_INCOME: "ADD_INCOME",
  REMOVE_EXPENSE: "REMOVE_EXPENSE",
  REMOVE_INCOME: "REMOVE_INCOME",
  UPDATE_INCOME_EXPENSE: "UPDATE_INCOME_EXPENSE",
};
