#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

exec >/dev/tty 2>&1

yarn precommit
# Check Prettier standards
# npm run check-format ||
# (
#     echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
#     false;
# )

# # Check ESLint Standards
# npm run lint ||
# (
#     echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
#     false; 
# )
